name: Code quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master, staging ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm biome ci